2020-01-25 14:00:28,113 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-25 14:06:54,912 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-27 09:47:56,255 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-27 09:48:02,820 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:03:14,075 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:04:19,498 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:07:07,119 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:07:57,404 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:23:57,661 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:24:56,533 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:28:26,815 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:44:02,962 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-01-30 07:44:10,884 ERROR: Exception on /user/alex [GET] [in c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\routes.py", line 78, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\templates\user.html", line 1, in <module>
    {% extends "base.html" %}
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\templates\user.html", line 14, in root
    </td>
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\templates\base.html", line 54, in root
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\templates\user.html", line 57, in block_content
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'unllow' with values ['username']. Did you mean 'unfollow' instead?
2020-01-30 07:45:40,841 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-02-01 14:30:23,436 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-02-01 14:30:56,714 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-02-01 14:35:59,089 INFO: Microblog startup [in C:\Users\alexa_aamkjbh\Desktop\microblog\app\__init__.py:48]
2020-02-01 14:36:01,989 ERROR: Exception on /explore [GET] [in c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\routes.py", line 33, in explore
    return render_template('index.html', title='Explore', posts=posts )
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\templates\index.html", line 2, in <module>
    {% extends "base.html" %}
  File "c:\users\alexa_aamkjbh\desktop\microblog\venv\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\templates\index.html", line 16, in root
    <p>{{ form.submit() }}</p>
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\templates\base.html", line 55, in root
  File "C:\Users\alexa_aamkjbh\Desktop\microblog\app\templates\index.html", line 46, in block_content
TypeError: 'Pagination' object is not iterable
